### ISSUE TITLE
FEATURE: New emulator specifically for Mario Paint

### ISSUE THREAD

**Issue by free5ty1e** [free5ty1e/primestationone#384]
Create a special entry with a special theme and special config file to auto launch Snes9x-Next (Pi2 only) with the SNES mouse enabled.  Will be only for Mario Paint ROMs (or if anyone ever hacks the SNES Mario Paint ROM into anything else fun).  Right now its a manual procedure to get Mario Paint working and the point of the Primestation One is to play all the things effortlessly from one's couch.

**Comment by pr1ntf** [comment]
I do know there is a hacked MarioPaint ROM with Joystick Support instead of mouse, but having the SNES mouse functionality would be nice for other games as well.

**Comment by free5ty1e** [comment]
Fixed with Pull Request #414
