### ISSUE TITLE
Possible controller bug

### ISSUE THREAD

**Issue by circuit-static** [free5ty1e/primestationone#62]
I noticed when I was playing original Zelda on NES that holding select and L1 for save state also loads the game. This means anytime you have to save, you also pause the game and have to un-pause after. Just thought you would like to know :-)

**Comment by free5ty1e** [comment]
That is odd and unintentional.  I'll look into this; I've also wanted to have the NES emulation changed to use X as the A button and Square as the B button as this also feels far more natural, having gamed on a real NES for the majority of my youth :D

**Comment by free5ty1e** [comment]
Fixed as of v0.9997beta (and probably way earlier)
