### ISSUE TITLE
No BIOS found on PS Emulator

### ISSUE THREAD

**Issue by circuit-static** [free5ty1e/primestationone#65]
When launching Frogger on PS emulator, got a No Bios found, expect bugs error. Then it attempted to load but looked bad enough it wasn't playable.

**Comment by free5ty1e** [comment]
This should have been taken care of by `installMegaTools.sh` followed by `megaInstallBinsNRoms.sh` (or their equivalent entries on the emulationstation settings page).

It sounds as though you may have only run 'megaInstallBinsNRoms_Large.sh` and not the `megaInstallBinsNRoms.sh` script.  There is no overlap in these modules, the "large" one just contains larger items that are less useful per unit megabyte than the smaller module :)

To ensure things are all set up correctly and make sure all the emulators that we use are actually built and installed, along with several other fixes and resets (removal of outdated scripts and ROMs, for instance - the latest version of the binsnroms modules also contains many individually ZIPped NES ROMs that would result in double listings in emulationstation if things weren't cleared out), you can prepare to leave the Primestation alone for the next 24ish hours and run this command:

```
quickUpdatePrimestationOneFiles.sh && primeStationOneFirstTimeSetupAndReset.sh
```

(It'll build all the emulators and emulationstation and retroarch and get the latest automatic joystick configs and all experimental fun stuff like Minecraft and Darkplaces Quake and all sorts of good stuff, but it'll take about a day or so of compiling.)

**Comment by free5ty1e** [comment]
Just reread what I wrote and realized it's not entirely clear: a quick fix SHOULD be to just run this script:

```
megaInstallBinsNRoms.sh
```

...assuming you have already run `installMegaTools.sh`.  The latest version of this module should take care of installing the BIOS files to the correct location to enable both FBA / NeoGeo and PSX.
